export default {
	ALL: '*',
	APP_STARTED: '/STARTUP',
	THREAD_DATA_LOADED: '/DATA/THREADS/LOADED',
	EMAIL_DATA_LOADED: '/DATA/EMAIL/LOADED',
	USER_DATA_LOADED: '/DATA/USER/LOADED',
	SET_SEARCH: '/CLIENT/SEARCH/SET',
}